apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wheel-of-names
resources:
  - namespace.yaml
  - deployment.yaml
  - pdb.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: wheel-of-names
    newName: harbor.example.local/tools/wheel-of-names
    newTag: "1.0.0"
